import express from 'express';
import Car from '../models/Car.ts';

const router = express.Router();

// GET - Obtenir toutes les voitures
router.get('/', async (req, res) => {
  const { categoryId } = req.query;
  try {
    const filter = categoryId ? { categoryId } : {};
    const cars = await Car.find(filter);
    res.json(cars);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// GET - Obtenir une voiture par ID
router.get('/:id', async (req, res) => {
  try {
    const car = await Car.findById(req.params.id);
    if (!car) {
      res.status(404).json({ error: 'Voiture non trouvée' });
      return;
    }
    res.json(car);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// POST - Créer une nouvelle voiture
router.post('/', async (req, res) => {
  try {
    // Note: ID is auto-generated by Mongo usually, but if we want to migrate existing
    // we might accept it, or better yet, let Mongo handle it.
    // The frontend sends 'id' sometimes but for new entries it might be just payload.
    // Let's create a new document with the body.
    const payload = { ...req.body };
    if (payload.id && !payload._id) {
      payload._id = payload.id;
    }
    if (payload.usage && !payload.carUsage) {
      payload.carUsage = payload.usage;
    }
    delete payload.id;
    delete payload.usage;

    const newCar = new Car(payload);
    const savedCar = await newCar.save();
    res.status(201).json(savedCar);
  } catch (error: any) {
    console.error('Create car error:', error);
    res.status(400).json({ error: error.message });
  }
});

// PUT - Modifier une voiture
router.put('/:id', async (req, res) => {
  try {
    const payload = { ...req.body };
    if (payload.usage && !payload.carUsage) {
      payload.carUsage = payload.usage;
    }
    delete payload.id;
    delete payload.usage;
    const updatedCar = await Car.findByIdAndUpdate(
      req.params.id,
      payload,
      { new: true, runValidators: true }
    );
    if (!updatedCar) {
      res.status(404).json({ error: 'Voiture non trouvée' });
      return;
    }
    res.json(updatedCar);
  } catch (error: any) {
    console.error('Update car error:', error);
    res.status(400).json({ error: error.message });
  }
});

// DELETE - Supprimer une voiture
router.delete('/:id', async (req, res) => {
  try {
    const deletedCar = await Car.findByIdAndDelete(req.params.id);
    if (!deletedCar) {
      res.status(404).json({ error: 'Voiture non trouvée' });
      return;
    }
    res.json({ message: 'Voiture supprimée avec succès' });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
